services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: streamcart
      POSTGRES_PASSWORD: streamcart
      POSTGRES_DB: streamcart
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
